SCHEMES = [
    {"id": "1", "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
     "description": "Direct income support of ₹6,000 per year in three equal installments to eligible landholding farmer families.",
     "eligibility": "Landholding farmer families, subject to exclusion criteria on the official portal",
     "benefits": "₹2,000 every 4 months transferred directly to the bank account",
     "website": "https://pmkisan.gov.in/", "category": "Financial Support"},
    {"id": "2", "name": "PMFBY (Pradhan Mantri Fasal Bima Yojana)",
     "description": "Crop insurance scheme providing financial support to farmers in case of crop loss from natural calamities, pests and diseases.",
     "eligibility": "Farmers growing notified crops in notified areas (check with your bank/CSC)",
     "benefits": "Insurance cover against yield loss at low farmer premium rates",
     "website": "https://pmfby.gov.in/", "category": "Insurance"},
    {"id": "3", "name": "Soil Health Card Scheme",
     "description": "Provides farmers with a soil health card containing soil nutrient status and crop-wise fertiliser recommendations.",
     "eligibility": "All farmers", "benefits": "Soil testing and nutrient/fertiliser recommendations for your field",
     "website": "https://soilhealth.dac.gov.in/", "category": "Soil Management"},
    {"id": "4", "name": "PMKSY (Pradhan Mantri Krishi Sinchayee Yojana)",
     "description": "Irrigation scheme focused on expanding irrigated area and improving water-use efficiency ('Per Drop More Crop') including micro-irrigation support.",
     "eligibility": "Farmers adopting drip/sprinkler and other irrigation improvements (state-specific)",
     "benefits": "Subsidy support for micro-irrigation systems and water conservation works",
     "website": "https://pmksy.gov.in/", "category": "Irrigation"},
    {"id": "5", "name": "Kisan Credit Card (KCC)",
     "description": "Credit facility for farmers to meet short-term credit requirements for cultivation and allied activities.",
     "eligibility": "Farmers including tenant farmers, oral lessees and sharecroppers",
     "benefits": "Timely credit access at concessional interest with flexible repayment",
     "website": "https://www.india.gov.in/spotlight/kisan-credit-card-kcc-scheme", "category": "Credit Facility"},
    {"id": "6", "name": "e-NAM (National Agriculture Market)",
     "description": "Pan-India electronic trading portal networking APMC mandis for transparent online trading of agricultural commodities.",
     "eligibility": "Farmers, traders and FPOs registered on the portal",
     "benefits": "Transparent price discovery and access to more buyers",
     "website": "https://www.enam.gov.in/", "category": "Market Linkage"},
    {"id": "7", "name": "PKVY (Paramparagat Krishi Vikas Yojana)",
     "description": "Promotes organic farming through cluster-based approach with PGS certification.",
     "eligibility": "Groups/clusters of farmers adopting organic farming",
     "benefits": "Financial assistance for organic inputs, training and certification (see official site for current norms)",
     "website": "https://pgsindia-ncof.gov.in/", "category": "Organic Farming"},
    {"id": "8", "name": "MSP (Minimum Support Price)",
     "description": "Government-announced minimum prices for notified crops each season to protect farmers from price falls; procurement through designated agencies.",
     "eligibility": "Farmers selling notified crops at procurement centres (registration rules vary by state)",
     "benefits": "Assured minimum price for notified crops",
     "website": "https://agriwelfare.gov.in/en/MSP", "category": "Price Support"},
    {"id": "9", "name": "PM-KUSUM",
     "description": "Solar pumps and grid-connected solar power for farmers to secure irrigation and earn additional income.",
     "eligibility": "Individual farmers, cooperatives, panchayats, FPOs",
     "benefits": "Central and state subsidy on solar pumps (see official site for current rates)",
     "website": "https://pmkusum.mnre.gov.in/", "category": "Solar Energy"},
    {"id": "10", "name": "Kisan Call Centre",
     "description": "Toll-free helpline providing expert advice on agriculture-related queries in local languages.",
     "eligibility": "All farmers", "benefits": "Expert guidance by phone", "phone": "1800-180-1551",
     "website": "https://mkisan.gov.in/", "category": "Advisory Services"},
    {"id": "11", "name": "PM Kisan Maan Dhan Yojana",
     "description": "Voluntary contributory pension scheme for small and marginal farmers.",
     "eligibility": "Small and marginal farmers aged 18-40 (see portal for details)",
     "benefits": "Monthly pension after age 60",
     "website": "https://maandhan.in/", "category": "Pension Scheme"},
]
